name: "On Push, rebuild the .BA file from the .DO file and publish as a pre-release"

on:
  push:

jobs:
  build_release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Create tar and zip files
      run: make archive
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          name: autobuild
          draft: false
          prerelease: true
          generate_release_notes: true
          files: |
            MIAM.tar.gz
            MIAM.zip
            MIAM.BA
            MIAM.DO
